name = 'chess_on_cardano/1_the_turn_token'
version = '0.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project 'pgrange/1_the_turn_token'"

[repository]
user = 'chess_on_cardano'
project = '1_the_turn_token'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = 'main'
source = 'github'
